name: jaspr_ui
description: A starting point for Dart libraries or applications.
version: 1.1.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.5.3

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0
dependencies:
  jaspr: ^0.16.1
  jaspr_router: ^0.6.0

dev_dependencies:
  jaspr_lints: ^0.1.2
  lints: ^4.0.0
  test: ^1.24.0

jaspr:
  mode: static
