name: jaspr_ui
description: A starting point for Dart libraries or applications.
version: 1.1.0
repository: https://github.com/anoochit/jaspr_ui
publish_to: none
environment:
  sdk: ">=3.5.3 <4.0.0"
dependencies:
  jaspr: ^0.17.0
  jaspr_router: ^0.6.1
  jaspr_svg:
    path: packages/jaspr_svg/
dev_dependencies:
  jaspr_lints: ^0.1.2
  lints: ^4.0.0
  test: ^1.24.0
jaspr:
  mode: static
